### ISSUE TITLE
association.php: rajouter les infos pour chaque association

### ISSUE THREAD

**Issue by encorpaulo** [Benevolink/Website#87]
Rajouter les infos de l'asso: adresse, mail, téléphone, description de l'asso et domaine qui sont sur la bdd, comme sur le mockup (on s'occupera du front)

![image](https://github.com/Benevolink/Website/assets/66567466/79ee9d03-110f-4d05-86ad-d53bf43eb147)

**Comment by Zeilor** [comment]
J'ai fait sur la branche ajout_details_association.php
Je t'invite à rapidos switch dessus pour tester en local et voir si tu veux ajouter / changer un truc.
En attendant je merge pas encore et je close pas l'Issue.
